INSERT INTO EMPLOYEES(employee_id,
        department_id,
        email,
        first_name,
        hire_date,
        last_name,
        manager_id,
        phone_number,
        salary) values(1,1,'saqib@email.com','saqib','2021-08-08','Ali',1,'03001111111',1000);
INSERT INTO EMPLOYEES(employee_id,
        department_id,
        email,
        first_name,
        hire_date,
        last_name,
        manager_id,
        phone_number,
        salary) values(2,1,'ahmed@email.com','ahmed','2021-08-07','mujahid',1,'03001111111',1000);
INSERT INTO EMPLOYEES(employee_id,
        department_id,
        email,
        first_name,
        hire_date,
        last_name,
        manager_id,
        phone_number,
        salary) values(3,1,'sameer@email.com','sameer','2021-08-06','Ahmed',1,'03001111111',1000);
INSERT INTO EMPLOYEES(employee_id,
        department_id,
        email,
        first_name,
        hire_date,
        last_name,
        manager_id,
        phone_number,
        salary) values(4,1,'ahsen@email.com','ahsen','2021-08-05','qadeer',1,'03001111111',1000);
INSERT INTO EMPLOYEES(employee_id,
        department_id,
        email,
        first_name,
        hire_date,
        last_name,
        manager_id,
        phone_number,
        salary) values(5,1,'ali@email.com','ali','2021-08-04','khan',1,'03001111111',1000);
INSERT INTO EMPLOYEES(employee_id,
        department_id,
        email,
        first_name,
        hire_date,
        last_name,
        manager_id,
        phone_number,
        salary) values(6,1,'tahir@email.com','tahir','2021-08-03','baloch',1,'03001111111',1000);


